// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBwDv6jsMRhcRnKqZU5YmtRHgt0AZV-vs',
    appId: '1:908929141371:web:e88e7eb9ba54cd7670b0de',
    messagingSenderId: '908929141371',
    projectId: 'hackathon-26ead',
    authDomain: 'hackathon-26ead.firebaseapp.com',
    storageBucket: 'hackathon-26ead.appspot.com',
    measurementId: 'G-8EBP113G5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuz1FNi13iguiaubPR0qb-cLS075Rr1Vg',
    appId: '1:908929141371:android:2282dac92b1ac58b70b0de',
    messagingSenderId: '908929141371',
    projectId: 'hackathon-26ead',
    storageBucket: 'hackathon-26ead.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBYxbxPiqOyKpfHkiZH6HdvC4kkEccJg0',
    appId: '1:908929141371:ios:424f1f05cf6e26fa70b0de',
    messagingSenderId: '908929141371',
    projectId: 'hackathon-26ead',
    storageBucket: 'hackathon-26ead.appspot.com',
    androidClientId: '908929141371-5o6vj0e62lu3uhvlouafgstp5433b9pt.apps.googleusercontent.com',
    iosClientId: '908929141371-0qav6mgefcnhnnvjbrioc1fd4p85i901.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathonProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBYxbxPiqOyKpfHkiZH6HdvC4kkEccJg0',
    appId: '1:908929141371:ios:424f1f05cf6e26fa70b0de',
    messagingSenderId: '908929141371',
    projectId: 'hackathon-26ead',
    storageBucket: 'hackathon-26ead.appspot.com',
    androidClientId: '908929141371-5o6vj0e62lu3uhvlouafgstp5433b9pt.apps.googleusercontent.com',
    iosClientId: '908929141371-0qav6mgefcnhnnvjbrioc1fd4p85i901.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathonProject',
  );
}
