// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgqAIrdz4ILZS4JF1PweU3tT9F7Ero5fs',
    appId: '1:901982379502:web:91da3a084d33e6a71b02ff',
    messagingSenderId: '901982379502',
    projectId: 'hackathon-project-9277d',
    authDomain: 'hackathon-project-9277d.firebaseapp.com',
    storageBucket: 'hackathon-project-9277d.appspot.com',
    measurementId: 'G-5ZX1CTRYEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Obm6Vx8_V3PGIP1-buk3bSGrklT6Yew',
    appId: '1:901982379502:android:725e49cb61e8edf31b02ff',
    messagingSenderId: '901982379502',
    projectId: 'hackathon-project-9277d',
    storageBucket: 'hackathon-project-9277d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXdJKWYGp_WTQQ_jkeTUSgP1N9RyMh3tU',
    appId: '1:901982379502:ios:550f4feefe2b561f1b02ff',
    messagingSenderId: '901982379502',
    projectId: 'hackathon-project-9277d',
    storageBucket: 'hackathon-project-9277d.appspot.com',
    iosClientId: '901982379502-3ql8aco9n42rglm0cg14mrkfckl47vns.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathonProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXdJKWYGp_WTQQ_jkeTUSgP1N9RyMh3tU',
    appId: '1:901982379502:ios:550f4feefe2b561f1b02ff',
    messagingSenderId: '901982379502',
    projectId: 'hackathon-project-9277d',
    storageBucket: 'hackathon-project-9277d.appspot.com',
    iosClientId: '901982379502-3ql8aco9n42rglm0cg14mrkfckl47vns.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathonProject',
  );
}
